language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
install:
  - pip install -r requirements/basic.txt
  - pip install -r requirements/deep.txt
  - pip install -r requirements/probablistic.txt
script:
  - coverage run -m unittest discover
after_success:
  - bash <(curl -s https://codecov.io/bash)
